apiVersion: v1
kind: Service
metadata:
name: {{ template "memcached.fullname" . }}
labels:
    app: {{ template "memcached.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
type: {{ .Values.service.ssh.serviceType }}
ports:
    - name: http
    port: {{ .Values.service.http.port }}
    targetPort: 11211
selector:
    app: {{ template "memcached.fullname" . }}
